In [1]:
import numpy as np

Уровень 0
Придумайте матрицы, которые обладают следующими свойствами:
a) диагональная, ортогональная, но не единичная(!):
b) верхнетреугольная, ортогональная:
c) нижнетреугольная, ортогональная:
d) матрица, у которой определитель = 1, и все элементы не равны 0:
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

In [2]:
A = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]]) #все компонены равны нулю кроме диагонали, не единичная матрица
A

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [5]:
AT = np.transpose(A)
AT

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

чтобы понять отогональная матрица или нет умножим ее на нее саму только транспонированную

In [6]:
A @ AT

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
C = np.array([[1, 0, 0], [0, 1, 0], [0, 0, -1]]) #нижне..верхне треугольная и ортогональная
C

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [19]:
CT = np.transpose(C)
CT

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [20]:
C @ CT

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
CC = np.eye(3)

In [23]:
CCT = np.transpose(CC)
CC @ CCT


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
D = np.array([[10.5, 2.2], [0.5, 0.2]])
D

array([[10.5,  2.2],
       [ 0.5,  0.2]])

In [115]:
det = np.linalg.det(D)
det

1.0

In [116]:
m = np.array([[2, 2],
[1, 3]])
print(m)

[[2 2]
 [1 3]]


In [117]:
w, v = np.linalg.eig(m)

In [126]:
for i in range(len(w)):
    print(f'Собственному значению {w[i]} соответствует собственный вектор {v[:,i]}')

Собственному значению 1.0 соответствует собственный вектор [-0.89442719  0.4472136 ]
Собственному значению 4.0 соответствует собственный вектор [-0.70710678 -0.70710678]
